### PR TITLE
Automatically execute generateIcons task when assembling android apk

### LINKED ISSUE #4: Integrate Icon Generation Task with the "Build" Lifecycle
## Description

The icon generation task currently needs to be run manually. 

This feature would involve hooking the task into the Gradle build lifecycle, allowing it to be executed automatically when running the standard build tasks. This improvement will streamline the developer experience by removing the need for manual execution.

### PR DESCRIPTION
**Pull request by mr3y-the-programmer**
This removes the need for a manual `generateIcons` task execution.

A few notes that can help in reviewing this PR:

- This feature makes use of `withPlugin` API to run the configuration block at the right time ensuring that it only runs after the Android Gradle Plugin has been applied.
- It also uses `onVariants` API from AGP to declare the dependency per variant to make sure we're running `generateIcons` task before any variant specific `assemble` task (i.e `assembleDebug`, `assembleRelease`, `assembleStaging`...etc)

Tip: to quickly see the dependencies of a specific task without actually executing it, run `.\gradlew <task-name> --dry-run` (e.g `.\gradlew assembleDebug --dry-run`). This is especially helpful for tasks that have a long execution time and you only need to know which tasks are triggered when they run.

Fixes #4

### CODE REVIEW

**Comment by qamarelsafadi** [comment]
Hi @mr3y-the-programmer ,

Thank you for the detailed PR and the improvements you've made! looks promising and should indeed help streamline the `generateIcons` task execution.

However, when testing the changes on my end, I noticed that the generateIcons task is not being triggered during the build, run, or even sync processes. I’ve tried running the commands you mentioned, but it seems the task isn’t getting picked up as expected.

Could you please double-check the integration to ensure the task is correctly hooked into the build lifecycle? Let me know if there's anything specific I should verify on my side.

Thanks again for your contribution! 🥳🙌🏼

**Comment by mr3y-the-programmer** [comment]
Just to confirm we're on the same page, Can you share the process of testing these changes?
Mine is like this:

1. Pull the changes downstream to my local repository.
2. Update the version in plugin's [build.gradle.kts](https://github.com/qamarelsafadi/KMPAppIconGeneratorPlugin/blob/main/build-logic/build.gradle.kts#L8) file to `1.2.3`.
3. publish the changes to `mavenLocal` repository declared in your settings.gradle.kts by running `./gradlew publishToMavenLocal`.
4. Update the version of the plugin in the sample [build.gradle.kts](https://github.com/qamarelsafadi/KMPAppIconGeneratorPlugin/blob/main/composeApp/build.gradle.kts#L11) to match the version you've set in step 2.
5. Sync gradle changes (if you want to run the task from the IDE, otherwise ignore this step)

Assuming you've followed the above instructions, then you should be able to see `generateIcon` task gets triggered whenever you build the android app(i.e by running `./gradlew assembleDebug` or `./gradlew assembleRelease`)

Also, to make sure your setup is correct, try running  `./gradlew assembleDebug --dry-run` and you should inspect `generateIcon` task in the output of running this command:
Capture
As you can see, the screenshot from my machine shows that `generateIcon` task is indeed a dependency for `assembleDebug` task

**Comment by mr3y-the-programmer** [comment]
I've tested the changes again on my machine and I can confirm it works, so let me know if you've any other problems in your local setup

**Comment by qamarelsafadi** [comment]
checked and yes it shall work fine, please take a pull from the main first then we can merge 🥳!  @mr3y-the-programmer

**Comment by mr3y-the-programmer** [comment]
@qamarelsafadi Done ✅

**Comment by qamarelsafadi** [comment]
Great job @mr3y-the-programmer 🚀! 

To ensure the iOS build automatically triggers the generateIcons task just like we did for Android, you can add the following lines to the plugin:

```kotlin
project.afterEvaluate {
    project.extensions.findByType(org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension::class.java)?.targets
        ?.withType(KotlinNativeTarget::class.java)?.configureEach {
            this.binaries.getFramework("Debug").linkTask.dependsOn(generateIconsTaskProvider)
            this.binaries.getFramework("Release").linkTask.dependsOn(generateIconsTaskProvider)
        }
}

```

This code ensures that after the project configuration is fully evaluated, we access the Kotlin Multiplatform Extension to target the native (iOS) binaries. We then configure the iOS frameworks (both Debug and Release), making their linkTask—the task responsible for linking the framework—depend on the generateIconsTaskProvider. This way, every time the iOS framework is built, whether in Debug or Release, the icons are generated first, ensuring the latest icons are included in the build.

It would be awesome if you could add this to your PR to leverage your work even further and ensure that the plugin works seamlessly for both Android and iOS! 🙌

**Comment by mr3y-the-programmer** [comment]
I will add it, but FYI I'm not on Mac machine so I won't be able to test this, I'll need help from your side then on this 🙌.

 Also, `afterEvaluate` is known for causing some ordering issues and some nasty bugs, this is one of footguns in Gradle API surface 😅 if you don't know that, but I'm not aware of alternative API from IOS side for this usecase as I have very little knowledge in the IOS, MacOS part, that being said I think we'll keep using it as long as it works fine, What do you think?

**Comment by qamarelsafadi** [comment]
good catch! wasn't know about it, I believe we can use the following instead ( tried it on my machine and it works fine ) : 

```kotlin 
        project.plugins.withType(org.jetbrains.kotlin.gradle.plugin.KotlinMultiplatformPluginWrapper::class.java) {
            project.extensions.findByType(org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension::class.java)?.targets
                ?.withType(KotlinNativeTarget::class.java)?.configureEach {
                    binaries.all {
                        linkTask.dependsOn(generateIconsTaskProvider)
                    }
                }
        }
```

**Comment by mr3y-the-programmer** [comment]
@qamarelsafadi Added it, let me know if you experience any issues with it

**Comment by qamarelsafadi** [comment]
@mr3y-the-programmer PERFECT! thanks a lot for this incredible effort 🙌🏼!

**Pull request merged**
